# Resource

 https://stackoverflow.com/questions/42068474/tfidfvectorizer-how-does-the-vectorizer-with-fixed-vocab-deal-with-new-words

# Search keywords

In [2]:
s2orc_pdf = '/home/sumeetkd/codes/Quazar/purchaser/S2ORC/s2orc/data/pdf_parses/sample.jsonl'

In [3]:
import io, json, re
from tqdm import tqdm
pattern = re.compile('Agilent')
with open(s2orc_pdf, 'r') as f_out:
    for line in tqdm(f_out.readlines()):
        pdf_parse = json.loads(line)
        sections = pdf_parse['body_text']
        for section in sections:
            print(section['text'])
            break
        break

  0%|          | 0/203 [00:00<?, ?it/s]

Values are presented as number only or median (range). 


In [61]:
pattern = re.compile('the')
corpus = []
with open(s2orc_pdf, 'rb') as myfile:
    head = [next(myfile) for x in range(160)]
    for line in tqdm(head):
        pdf_parse = json.loads(line)
        #print(pdf_parse['paper_id'],'\n')
        sections = pdf_parse['body_text']
        #print(section.keys())123
        for section in sections:
            if pattern.findall(section['text']):
                #print(section['section'])
                corpus.append(section['text'])

100%|██████████| 160/160 [00:00<00:00, 1897.11it/s]


In [62]:
len(corpus)

1833

In [78]:
s2orc_pdf = '/home/sumeetkd/codes/Quazar/purchaser/S2ORC/s2orc/data/pdf_parses/sample.jsonl'
with open(s2orc_pdf, 'rb') as myfile:
    for line in tqdm(myfile):
        metadata = json.loads(line)
        paper_id = metadata['paper_id']
        print(paper_id)

203it [00:00, 1296.05it/s]

77499681
94550656
94551239
94551546
94552339
94553452
94555004
94556881
94559152
159350887
159352431
159355456
159355939
159358374
159359827
18980190
18980380
18980463
18980811
18981111
18981201
18981319
18981336
18981358
18981625
18982114
18982127
18982341
18982460
18982496
18982504
18982512
18982781
18983082
18983391
18984129
18984386
18984455
18984609
18984674
18984807
18985171
18985891
18986705
18986901
18987532
18987535
18987990
18988046
18988104
18988615
18989067
18989187
18989350
18989559
18989713
18989842
199660318
199661662
199661683
199661892
199661969
199662147
199662295
199662866
199664249
199664457
199664595
199664911
199664931
199665186
199665266
199665542
199665735
199665950
199666740
199666746
199666823
199666980
199667935
199667938
199668067
199668072
199668440
199668529
199668547
199668877
199668887
199668943
199669259
199669503
2870029
2870075
2870145
2870252
2870542
2870829
2870859
2871179
2871295
2871533
2871546
2871630
2871678
2871844
2871896
2871940
2872418
28725

# Loading subject abstracts

## Final reading of gzip files

In [2]:
import gzip,io,tqdm,json
abstracts = []
paper_ids = []
with gzip.open('/home/sumeetkd/codes/Quazar/purchaser/S2ORC/sample/20200705v1/full/metadata/metadata_0.jsonl.gz','rb') as gz:
    f = io.BufferedReader(gz)
    for line in f:
        metadata_dict = json.loads(line)
        paper_id = metadata_dict['paper_id']
        mag_field_of_study = metadata_dict['mag_field_of_study']
        abstract = metadata_dict['abstract']
        # [TODO] add pdf abstract reader in case absent
        if mag_field_of_study and 'Physics' in mag_field_of_study and abstract != None:
            paper_ids.append(paper_id)
            abstracts.append(abstract)

In [113]:
sys.getsizeof(abstracts)

457344

In [114]:
len(abstracts)

53364

53364

The abstracts for a particular field coming out from a shard amount to less than 1 MB. 

## Reading from second gzip

In [115]:
import gzip,io,tqdm,json
abstracts_1 = []
with gzip.open('/mnt/DataSource/20200705v1/full/metadata/metadata_1.jsonl.gz','rb') as gz:
    f = io.BufferedReader(gz)
    for line in f:
        metadata_dict = json.loads(line)
        paper_id = metadata_dict['paper_id']
        mag_field_of_study = metadata_dict['mag_field_of_study']
        abstract = metadata_dict['abstract']
        # [TODO] add pdf abstract reader in case absent
        if mag_field_of_study and 'Physics' in mag_field_of_study and abstract != None:
            paper_ids.append(paper_id)
            abstracts_1.append(abstract)

In [26]:
len(abstracts_1)

53423

In [25]:
sys.getsizeof(abstracts_1)

457344

## Creating batches

In [ ]:
import gzip,io,tqdm,json
abstracts = []
paper_ids = []
with gzip.open('/home/sumeetkd/codes/Quazar/purchaser/S2ORC/sample/20200705v1/full/metadata/metadata_0.jsonl.gz','rb') as gz:
    f = io.BufferedReader(gz)
    for line in f:
        metadata_dict = json.loads(line)
        paper_id = metadata_dict['paper_id']
        mag_field_of_study = metadata_dict['mag_field_of_study']
        abstract = metadata_dict['abstract']
        # [TODO] add pdf abstract reader in case absent
        if mag_field_of_study and 'Physics' in mag_field_of_study and abstract != None:
            paper_ids.append(paper_id)
            abstracts.append(abstract)

# Define Tokenization

In [3]:
import spacy
nlp = spacy.load("en_core_web_sm")

Rules for choosing tokenization
Drop stop words and punctuations

In [4]:
def spacy_tokenizer(document):
    tokens = nlp(document)
    tokens = [token.lemma_ for token in tokens if (
        token.is_stop == False and \
        token.is_punct == False and \
        token.lemma_.strip()!= '')]
    return tokens

In [63]:
corpus[0]

'Gene therapy holds potential for treating many severe diseases, such as cancer and genetic diseases. 1 Successful gene therapy depends on highefficiency gene delivery processes, in which the gene carriers have an essential role. The application of traditional viral vectors has been a challenge because of their toxicity, immunogenicity and low capability for scaling up. 2 There has long been a scientific demand for developing non-viral gene delivery systems that can overcome the drawbacks of viral vectors. 3 Non-viral gene delivery has been advanced by the rapid development of materials science and technology. Numerous novel gene delivery systems have been proposed based on functional cationic polymers, such as polyethylenimine (PEI), [4] [5] [6] [7] [8] [9] poly(2-(dimethylamino) ethyl methacrylate), 4,10 poly(L-lysine), 11 poly(aspartic acid) 12, 13 and polyamidoamine. 14 However, these non-viral gene carriers still have shortcomings, including cytotoxicity, low transfection efficien

In [44]:
spacy_tokenizer(corpus[0])

['plasmid',
 'prl',
 'CMV',
 'reporter',
 'gene',
 'utilize',
 'estimate',
 'vitro',
 'gene',
 'transfection',
 'PGMA',
 'base',
 'polycation',
 'pdna',
 'polyplexe',
 'C6',
 'Hep',
 'G2',
 'cell',
 'line',
 'essentially',
 'C6',
 'Hep',
 'G2',
 'cell',
 'culture',
 '24well',
 'plate',
 'density',
 '6',
 '×',
 '10',
 '4',
 'cell',
 'DMEM',
 'medium',
 '10',
 'fetal',
 'bovine',
 'serum',
 'solution',
 'polycation',
 'pdna',
 'complex',
 'different',
 'n',
 'p',
 'ratio',
 '20',
 'μl',
 '1.0',
 'μg',
 'pdna',
 'add',
 'transfection',
 'medium',
 'detailed',
 'transfection',
 'procedure',
 'describe',
 'early',
 'work',
 '15',
 '16',
 '32',
 '33',
 'commercial',
 'promega',
 'kit',
 'luminometer',
 'Berthold',
 'Lumat',
 'LB',
 '9507',
 'Berthold',
 'Technologies',
 'GmbH',
 'KG',
 'Bad',
 'Wildbad',
 'Germany',
 'quantify',
 'luciferase',
 'gene',
 'expression',
 'gene',
 'expression',
 'result',
 'express',
 'relative',
 'light',
 'unit',
 'milligram',
 'cell',
 'protein',
 'lysate',
 

# Seed vocabulary

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

Running the same code for the seed document
Had to use the suggestion in https://stackoverflow.com/questions/42068474/tfidfvectorizer-how-does-the-vectorizer-with-fixed-vocab-deal-with-new-words to get the vocabulary from a single document.
The attribute vocabulary_ is a dictionary with index and token.

One has to use TfidfVectorizer with this tokenizer because numerical values get attached with each work

In [6]:
token_run = TfidfVectorizer(input = 'content', tokenizer = spacy_tokenizer)
tokensrun = token_run.fit_transform([abstracts[0]])
len(token_run.vocabulary_)
vocab = token_run.vocabulary_

In [9]:
vocab

{'site': 43,
 'preference': 37,
 'ir': 22,
 'temperature': 50,
 'dependence': 10,
 'magnetic': 28,
 'susceptibility': 48,
 'low': 27,
 'specific': 44,
 'heat': 18,
 'β': 58,
 'mn1−xirx': 30,
 'alloy': 3,
 'investigate': 21,
 'phase': 34,
 'exist': 15,
 'x': 57,
 '=': 2,
 '0.102': 0,
 'ray': 40,
 'diffraction': 11,
 'pattern': 33,
 'atom': 5,
 'substitute': 47,
 '1': 1,
 'mn': 29,
 'lattice': 24,
 'electronic': 13,
 'coefficient': 6,
 'γ': 59,
 'proportional': 38,
 'neel': 31,
 'tn': 51,
 'form': 16,
 'tn3/4': 52,
 'region': 41,
 'concentration': 7,
 'increase': 19,
 'gradual': 17,
 'decrease': 9,
 'lead': 25,
 'relative': 42,
 'straight': 46,
 'line': 26,
 'conclude': 8,
 'state': 45,
 'vary': 54,
 'weak': 56,
 'itinerant': 23,
 'electron': 12,
 'antiferromagnet': 4,
 'intermediate': 20,
 'point': 36,
 'observe': 32,
 'versus': 55,
 'plot': 35,
 'universal': 53,
 'system': 49,
 'entire': 14,
 'range': 39}

Using the above vocabulary to run the vectorizer on the entire corpus

In [65]:
tfidf_vector = TfidfVectorizer(input = 'content', vocabulary = vocab)
result = tfidf_vector.fit_transform(corpus)
#if (token_run.vocabulary_ == tfidf_vector.vocabulary_):
#    print(True)

There is a problem with this method.
There could be words in the other abstracts which have similar lemma's once processed by spacy but because the processing was not done for them the information is lost.

# Large corpus

## Lazy loading

The best way for the system to work for me would be if I am able to do lazy loading

# Size of results

In [66]:
len(tfidf_vector.vocabulary_)

79

412 items in the list of tokens. A lot of useless words have seeped into this list. There has to be a better way to tokenize.
New vocabulary leads to a change in the shape

In [23]:
import sys

In [69]:
result.shape

(1833, 79)

In [71]:
sys.getsizeof(result)

48

Let us see if the system fails and then move to the next thing

# CountVectorizer

Because the size of the corpus is quite large, we want to analyze the documents one at a time, to pull out the term frequency per document and run the IDF later once we have complete information.

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer(input='content', vocabulary=vocab)

In [15]:
counts = count_vector.fit_transform(abstracts)

In [46]:
print(counts.shape,
counts_1.shape)

(53364, 60) (53423, 60)


In [28]:
type(counts)

scipy.sparse.csr.csr_matrix

In [41]:
counts_1[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
counts_1 = count_vector.fit_transform(abstracts_1)

In [10]:
from scipy.sparse import vstack

In [39]:
full = vstack([counts,counts_1])

In [42]:
full[53364].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
type(full)

scipy.sparse.csr.csr_matrix

## Loop stacking

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer(input='content', vocabulary=vocab)
for document in abstracts:
    counts = count_vector.fit_transform(document)
    print(list(document))
    try:
        matrix
        matrix = vstack(matrix,counts)
    except NameError:
        matrix = vstack(counts)
    break

ValueError: Iterable over raw text documents expected, string object received.

In [21]:
matrix = count_vector.fit_transform(abstracts)

In [22]:
matrix

<53364x60 sparse matrix of type '<class 'numpy.int64'>'
	with 98723 stored elements in Compressed Sparse Row format>

In [24]:
sys.getsizeof(matrix)

48

# TFIDFTransformer

In [99]:
from sklearn.feature_extraction.text import TfidfTransformer
transform = TfidfTransformer()

In [100]:
result = transform.fit_transform(full)

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html#sklearn.feature_extraction.text.TfidfTransformer.transform
Has made me feel that fit_transform should be converted to transform.
May have to be tested in some time

In [49]:
53364+53423

106787

In [51]:
sys.getsizeof(result)

48

In [88]:
result[9].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 3.72322259, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [60]:
0.5**2+0.87**2

1.0069

In [85]:
result_test = transform.fit_transform(full[9])

In [86]:
result_test.toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

There is a possibility that this calculation only deals with single document instead of the sum.
It might be that each vector is actually normalized. Simplifying the cosine similarity.
Pulling the idf_ matrix out and looking at the number and calling the Transformer without normalization
shows more reasonable values.
It is normalization!

In [84]:
transform.idf_

array([12.57860084, 12.57860084, 12.57860084,  5.95852763,  7.42530925,
        5.25477027,  4.65452851,  4.72344383,  5.81010763,  4.86749959,
        3.89758956,  4.63021555,  3.40554705,  4.52949312,  5.65595695,
        5.29652718,  3.83188449,  7.25072467,  4.30833173,  4.047702  ,
        5.23130114,  4.12200727,  5.6839308 ,  7.76641648,  4.38741484,
        4.74302159,  4.05781411,  3.07730875,  3.25136672,  6.21385008,
       12.57860084,  7.62277378,  5.34731384,  4.92605515,  3.172447  ,
        7.18952911,  3.89521547,  7.91516175,  5.40158207,  3.16108371,
        3.84114825,  3.72322259,  4.31346521,  5.53544092,  4.51964082,
        3.26805321,  6.4452028 ,  8.35909313,  5.77843077,  2.93174899,
        3.04032456,  8.05681226, 12.57860084,  5.73059557,  5.89649224,
        5.98692711,  4.64265574, 12.57860084, 12.57860084, 12.57860084])

In [79]:
full[9].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Cosine similarity matrix

In [94]:
from sklearn.metrics.pairwise import linear_kernel

In [55]:
cos_df = [ [ 0 for i in range(len(corpus)) ] for j in range(len(corpus)) ]

In [93]:
result[10]

<1x60 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [56]:
for i in range(len(corpus)):
    curr_cos_sim = linear_kernel(result[i:i+1], result).flatten()
    cos_df[i] = curr_cos_sim

The above matrix is for the reduced vocabulary and the lower one is for the complete vocabulary.
As you can see there are the lower values have become even lower and the higher values have increased.
Which makes sense.

In [57]:
cos_df

[array([1.        , 0.35742576, 0.03255663, 0.04803749, 0.01320895,
        0.16450696]),
 array([0.35742576, 1.        , 0.08864397, 0.01671493, 0.03596484,
        0.02085738]),
 array([0.03255663, 0.08864397, 1.        , 0.18856254, 0.40572238,
        0.23529381]),
 array([0.04803749, 0.01671493, 0.18856254, 1.        , 0.07650404,
        0.0443676 ]),
 array([0.01320895, 0.03596484, 0.40572238, 0.07650404, 1.        ,
        0.09546397]),
 array([0.16450696, 0.02085738, 0.23529381, 0.0443676 , 0.09546397,
        1.        ])]

The matrix is not required for the complete calculation. I only need to generate the single vector and keep values below a certain number.

In [101]:
cos_vector = linear_kernel(result[0],result).flatten()

In [96]:
len(cos_vector)

106787

In [117]:
for i in range(len(cos_vector)):
    if(cos_vector[i]>0.5):
        print(paper_ids[i])

94551733
212848771
12734688
121299667
111269941
62824450
1524750
120516622
120661898
122011684
3185812
123800178
120117731
52115422
120280905
55046007
124871465
128298978
124781275
117072727
39347270
113990997
121671340
118972429
123265753
122929139
118355429
40649689
123675267
122861089
15721065
117431057
117757255
125027275
121430800
119914501
121793427
29507435
25970692
121400895
122750063
124869437
119299890
121247456
100018553
121472610
120416053
54895312
203651849
102899
22093653


In [102]:
cos_vector

array([1.        , 0.27586522, 0.07364076, ..., 0.19852808, 0.        ,
       0.07995279])